			<div id="footer">
				Copyright &copy; <?php echo date("Y"); ?> CDepot. All rights reserved.
								<p style="visibility: hidden;">
      <a href="http://validator.w3.org/check/referer"><img
          src="http://www.w3.org/Icons/valid-xhtml10"
          alt="Valid XHTML 1.0!" height="31" width="88" border="0" /></a>
           | 
 <a href="http://jigsaw.w3.org/css-validator/">
  <img style="border:0;width:88px;height:31px"
       src="http://jigsaw.w3.org/css-validator/images/vcss" 
       alt="Valid CSS!" border="0" />
 </a> | 
  <a href="http://bobby.watchfire.com/" title="Bobby's Home Page">
<img src="approved_aaa.gif" alt="Bobby WorldWide Approved AAA" width="88" height="31" border="0" />
</a>
</p></div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2193958-8']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>