			<div id="navcontainer">
				<ul id="navlist">
					<li id="active"><a <?php if($name == 'home') echo ' id="current" '; ?> href="http://cdepot.com/index.php">Home</a></li>
					<li><a <?php if($name == 'locations') echo ' id="current" '; ?> href="http://cdepot.com/locations.php">Locations&nbsp;+&nbsp;Hours</a></li>
					<li><a <?php if($name == 'about') echo ' id="current" '; ?> href="http://cdepot.com/about.php">About&nbsp;Us</a></li>
					<li><a <?php if($name == 'mailinglist') echo ' id="current" '; ?> href="http://www.cdepot.com/list.php">Mailing&nbsp;List</a></li>
					<li><a <?php if($name == 'news') echo ' id="current" '; ?> href="http://www.cdepot.com/news.php">News</a></li>
					<li><a <?php if($name == 'sales') echo ' id="current" '; ?> href="http://www.cdepot.com/sales.php">ebay/half.com&nbsp;sales</a></li>
					<li><a <?php if($name == 'links') echo ' id="current" '; ?> href="http://www.cdepot.com/links.php">Links</a></li>
					<li><a <?php if($name == 'employment') echo ' id="current" '; ?> href="http://cdepot.com/jobs/">Employment</a></li>
				</ul>
				<p><b>Locations:</b></p>
				<div id="cp">
					<p>College Park:</p>
					<p>9039&nbsp;Baltimore&nbsp;Ave. College&nbsp;Park,&nbsp;MD&nbsp;20740</p>
					<p>301-982-3472</p>
				</div>
				<div id="towson">
					<p>Towson:</p>
					<p>8639&nbsp;Loch&nbsp;Raven Blvd. Towson,&nbsp;MD&nbsp;21234</p>
					<p>410-663-5720</p>
				</div>
			</div> 
